{
 "title": "Immich",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Immich Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{source=\"immich\"}"
    }
   ]
  },
  {
   "title": "Local Backup Borg Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{source=\"local_backup_borg\"}"
    }
   ]
  },
  {
   "title": "Remote Backup Borg Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{source=\"remote_backup_borg\"}"
    }
   ]
  },
  {
   "title": "Disk Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{source=\"data\"}"
    }
   ]
  },
  {
   "title": "Local Backup Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{source=\"local_backup\"}"
    }
   ]
  },
  {
   "title": "Remote Backup Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{source=\"remote_backup\"}"
    }
   ]
  },
  {
   "title": "Disk Last ran SmartCTL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{source=\"data\"}"
    }
   ]
  },
  {
   "title": "Local Backup Last ran SmartCTL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{source=\"local_backup\"}"
    }
   ]
  },
  {
   "title": "Remote Backup Last ran SmartCTL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{source=\"remote_backup\"}"
    }
   ]
  },
  {
   "title": "Local Backup Last ran Borg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{source=\"local_backup_borg\"}"
    }
   ]
  },
  {
   "title": "Remote Backup Last ran Borg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{source=\"remote_backup_borg\"}"
    }
   ]
  }
 ]
}